---
title: "projekt_zed"
author: "Andrzej Gauza"
date: "2024-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Podsumowanie analizy
**TODO**

# Biblioteki
``` {r}
library(dplyr)
library(ggplot2)
library(tidyr)
```

# Wczytanie danych
``` {r}
data <- read.csv("mp_batteries.csv")

columns <- names(data)
string_columns <- c("Battery.Formula", "Working.Ion", "Formula.Charge", "Formula.Discharge")
numeric_columns <- setdiff(columns, c(string_columns, "Battery.ID"))
#print(numeric_columns)
#print(string_columns)
```

# Podstawowe statystyki
```{r}
nrow(data)
summary(data)
```

# Analiza wartości atrybutów
### Atrybuty tekstowe
```{r}
counts <- data.frame()
for (col in string_columns)
{
  col_counts <- data %>%
    count(get(col), name = "Count") %>%
    arrange(desc(Count))
  col_counts$var <- col
  counts <- rbind(counts, col_counts)
  
  top_10_counts <- col_counts %>%
    slice(1:10)
  print(top_10_counts)
}

ggplot(counts, aes(x = Count)) +
geom_histogram(binwidth = 1, fill = "green", alpha = 0.7) +
labs(
  title = paste("Liczba wystąpień wartości dla zmiennej"),
  x = "Liczba wystąpień",
  y = "Liczba różnych wartości"
) +
facet_wrap(~var, scales="free") +
theme_minimal()
```

### Atrybuty liczbowe
```{r, fig.width=12, fig.height=12}
numeric_df <- data[, numeric_columns]
numeric_df_long <- numeric_df %>%
  pivot_longer(colnames(numeric_df)) %>% 
  as.data.frame()

ggplot(numeric_df_long, aes(x = value)) +
  geom_histogram(fill = "green", alpha = 0.7) + 
  facet_wrap(~ name, scales = "free") +
  theme_minimal()
```

# Korelacja
```{r}
numeric_df <- data[, numeric_columns]

# Calculate the correlation matrix
correlation_matrix <- cor(numeric_df)

# Convert the matrix to a data frame for saving
correlation_df <- as.data.frame(as.table(correlation_matrix))

# Rename the columns for clarity
names(correlation_df) <- c("x", "y", "cor")

correlation_df_one_dir <- correlation_df[as.character(correlation_df$x) < as.character(correlation_df$y), ]
```

Korelacja wszytskich par zmiennych numerycznych
```{r}
print(correlation_df_one_dir[order(-abs(correlation_df_one_dir$cor)), ])
```

```{r}
ggplot(correlation_df) +
  geom_tile(aes(x = x, y = y, fill = abs(cor))) +
  theme(axis.title = element_blank()) +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  scale_fill_gradient(low="white", high="green") +
  theme_minimal()
```

Przedstawienie korelacji dla 5 par zmiennych o najwyższej korelacji
```{r}
top_5_correlation <- correlation_df_one_dir[order(-abs(correlation_df_one_dir$cor)), ] %>%
  slice(1:5)

print(top_5_correlation)

for (i in 1:nrow(top_5_correlation)) {
  x_var <- top_5_correlation$x[i]
  y_var <- top_5_correlation$y[i]
  #print(x_var)
  #print(data[x_var])
  #print(y_var)
  
  # Dynamically create the plot
  #p <- ggplot(data, aes(x = x_var, y = y_var)) +
  #  geom_point() + # Scatter plot
  #  labs(title = paste("Plot of", x_var, "vs", y_var),
  #       x = x_var,
  #       y = y_var)
  
  # Print or save the plot
  #print(p) # Display the plot
}
#ggplot2()
```

